/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "primary": "#00497d",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#d6bee4",
        "on-primary-fixed-variant": "#00497d",
        "on-primary-container": "#c0dbff",
        "on-primary": "#FFFFFF",
        "on-secondary-fixed": "#101c2b",
        "on-secondary-fixed-variant": "#3c4858",
        "on-tertiary-container": "#e9d0f7",
        "surface-container-highest": "#e1e2e8",
        "surface-container-high": "#e6e8ee",
        "primary-fixed": "#d1e4ff",
        "inverse-primary": "#9fcaff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001d36",
        "on-tertiary-fixed": "#251431",
        "on-background": "#191c20",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bbc7db",
        "secondary": "#535f70",
        "primary-container": "#0061a4",
        "error": "#ba1a1a",
        "inverse-surface": "#2e3135",
        "surface-variant": "#DFE2EB",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#596576",
        "surface-container": "#eceef4",
        "surface-tint": "#0061a4",
        "secondary-container": "#d7e3f8",
        "on-error": "#ffffff",
        "tertiary-fixed": "#f3daff",
        "tertiary-container": "#6b5778",
        "secondary-fixed": "#d7e3f8",
        "primary-fixed-dim": "#9fcaff",
        "outline-variant": "#c1c7d2",
        "surface-container-low": "#f2f3fa",
        "on-surface-variant": "#414750",
        "on-tertiary-fixed-variant": "#523f5f",
        "background": "#f8f9ff",
        "surface": "#F8F9FF",
        "surface-dim": "#d8dae0",
        "on-surface": "#191c20",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#52405f",
        "inverse-on-surface": "#eff0f7",
        "outline": "#74777F"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "component-gap": "1rem",
        "sidebar-width": "280px",
        "editor-max-width": "800px",
        "container-padding": "2rem"
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "cv-serif": ["Noto Serif", "serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-small": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.15px", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "cv-serif": ["12px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["57px", { lineHeight: "64px", letterSpacing: "-0.25px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-small": ["11px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}